PROJECT-GSMC/GSMC-front

- .github/workflows/ci.yml
머지 후 Actions 탭에서 워크플로우 실행 여부 확인이 필요합니다
> Github Action CI 세팅

- apps/client/app/signup/page.tsx
- apps/client/src/entities/signin/api/postSignin.ts
- apps/client/src/entities/signin/model/usePostSignin.ts
- apps/client/src/entities/signup/api/patchVerifyEmail.ts
- apps/client/src/entities/signup/api/postSendEmail.ts
- apps/client/src/entities/signup/api/postSignup.ts
- apps/client/src/entities/signup/model/usePostSignup.ts
- apps/client/src/widgets/stepAuthCode/ui/index.tsx
인증코드 전송, 인증코드 검사, 회원가입 API 연결을 했습니다
- axios 인스턴스를 사용하도록 변경했습니다
> feat: signup 관련 API연결

- packages/ui/src/api/deleteCertification.ts
- packages/ui/src/card.tsx
> feat: 자격증 삭제 기능 구현

- packages/ui/src/list.tsx
> fix: list padding

- apps/client/app/foreign/page.tsx
- apps/client/src/shared/ui/dropdown/index.tsx
- apps/client/src/widgets/foreign/api/sendForeign.ts
- apps/client/src/widgets/foreign/lib/chooseDropdownOption.ts
- apps/client/src/widgets/foreign/model/foreign.ts
- apps/client/src/widgets/foreign/model/foreignOptions.ts
- apps/client/src/widgets/foreign/ui/foreignForm.tsx
> feat: 외국어 페이지 퍼블리싱, 기능개발

- apps/admin/src/entities/score/ui/checkbox.tsx
- apps/admin/src/shared/ui/header.tsx
- apps/admin/src/widget/score/ui/scoreForm.tsx
- packages/ui/src/list.tsx
> fix: 스코어 페이지 반응형 적용

- apps/client/app/signup/page.tsx
- apps/client/src/widgets/auth/ui/index.tsx
- apps/client/src/widgets/stepAuthCode/ui/index.tsx
- packages/ui/src/input.tsx
Input 컴포넌트의 props로 className을 추가하였습니다.
회원 가입 페이지에 반응형 디자인을 적용하였습니다.
https://github.com/user-attachments/assets/14fa3bf3-b2cc-48d3-be27-fb142be28970
https://github.com/user-attachments/assets/34d2abd0-b3f3-4c0f-ab6e-26038f664eef
아직 CORS 정책 위반 문제를 수정하지 않았습니다.
반응형 추가할 부분이 있는지 직접 테스트 해 보시면서 리뷰 달아주시길 바랍니다.
> fix: 회원 가입 페이지 반응형 디자인 적용

- apps/client/app/login/page.tsx
- apps/client/src/widgets/login/ui/index.tsx
> fix: 로그인 CSR 수정

- apps/client/src/shared/api/sendActivity.ts
- apps/client/src/widgets/book/api/sendBook.ts
- apps/client/src/widgets/foreign/api/sendForeign.ts
- apps/client/src/widgets/main/api/sendCertification.ts
- apps/client/src/widgets/main/api/sendEvidence.ts
- packages/ui/src/formAxios.ts
> fix: api 요청들을 수정 했습니다

- apps/client/src/widgets/main/api/sendCertification.ts
> fix: 자격증 등록 요청을 수정했습니다

- apps/client/app/example/page.tsx
> 예시 페이지 반응형 작업 했습니다.
> 화면이 줄어들때 title을 center로 맞췄는데 괜찮은지 의견 부탁드립니다!!
https://github.com/user-attachments/assets/24085d85-c551-4284-b0a2-771192c0a957
> fix: 예시 페이지 반응형 작업

- apps/admin/src/widget/check-post/ui/posts.tsx
- apps/client/src/widgets/posts/ui/myPosts.tsx
> admin 글 확인 페이지 반응형 제작했습니다
> 크기가 작아지면 제목이 더 작아지게 했는데 괜찮은지 봐주세요
https://github.com/user-attachments/assets/55800da5-7c4b-406b-a6ef-59bcdc17f52f
> fix: admin 글 확인 페이지 반응형

- apps/client/app/page.tsx
https://github.com/user-attachments/assets/592ae322-e8cf-4c01-8b04-33fa43abea61
로딩 디자인 추천 좀 해주세요
> feat: main isLoading

- apps/admin/package.json
- apps/client/package.json
> fix: build error

- apps/client/app/calculate/page.tsx
- apps/client/src/shared/ui/dropdown/index.tsx
- apps/client/src/widgets/calculate/ui/index.tsx
calculate 페이지 반응형 작업했습니다.
https://github.com/user-attachments/assets/acf6e958-aaa9-40fb-99a1-009fb1b1be6c
> feat: calculate 페이지 반응형

- apps/client/src/entities/main/ui/dropdown.tsx
- apps/client/src/entities/main/ui/showInformation.tsx
- apps/client/src/shared/ui/dropdown/index.tsx
- apps/client/src/shared/ui/header/index.tsx
- apps/client/src/views/main/ui/index.tsx
- apps/client/src/widgets/main/api/sendCertification.ts
- apps/client/src/widgets/main/api/sendEvidence.ts
- apps/client/src/widgets/main/model/options.ts
- apps/client/src/widgets/main/ui/modal.tsx
- packages/ui/src/button.tsx
> 모달 반응형을 수정하고 api 요청을 수정했습니다
> 테스트가 완료되지 않아서 나중에 다시 pr을 올릴 수도 있습니다
> fix: 모달 반응형 수정

- apps/client/src/entities/signin/api/postSignin.ts
- apps/client/src/entities/signup/api/patchVerifyEmail.ts
- apps/client/src/entities/signup/api/postSendEmail.ts
- apps/client/src/entities/signup/api/postSignup.ts
- apps/client/src/shared/model/AuthForm.ts
- apps/client/src/shared/types/error.ts
- apps/client/src/views/signin/ui/index.tsx
- apps/client/src/views/signup/ui/index.tsx
- apps/client/src/widgets/stepAuthCode/ui/index.tsx
- apps/client/src/widgets/stepPassword/ui/index.tsx
signin, signup page의 error message 작업
signup page의 step별 form 관리 작업
`
throw new Error(error.response.data.error || "")
->  throw error.response.data || ""
`
> fix: auth Error Handling

- apps/client/src/shared/api/sendScore.ts
- apps/client/src/shared/lib/handleSubmitActivity.ts
- apps/client/src/views/book/lib/handleBookSubmit.ts
- apps/client/src/views/book/ui/index.tsx
- apps/client/src/views/foreign/api/sendForeign.ts
- apps/client/src/views/foreign/model/foreignOptions.ts
- apps/client/src/views/foreign/ui/foreignForm.tsx
- apps/client/src/views/humanity/model/category.ts
- apps/client/src/views/humanity/ui/index.tsx
- apps/client/src/views/main/ui/index.tsx
- apps/client/src/views/major/model/category.ts
- apps/client/src/views/major/ui/index.tsx
- apps/client/src/widgets/main/model/evidence.ts
- apps/client/src/widgets/main/ui/modal.tsx
> fix: 글 추가 요청들을 수정

- apps/admin/next.config.ts
- apps/client/next.config.ts
- apps/client/src/widgets/stepAuthCode/ui/index.tsx
> 회원가입 페이지에서 스팸 메일함 확인 메시지 추가 했습니다
>
> feat: signup message

- .github/workflows/ci.yml
> fix: auth ci

- .github/workflows/ci.yml
- apps/client/src/views/detail/index.tsx
- apps/client/src/views/example/index.tsx
- package.json
- packages/types/src/evidences.ts
- pnpm-lock.yaml
mock을 통한 예시 페이지 상세보기를 추가 하였습니다.
mock이 존재하더라도 useGetPosts 호출이 되는데 react의 hook 호출 조건 중 조건식을 사용하면 안되는 조건 때문에 따로 처리를 하지 못했습니다.
> fix: example detail

- apps/admin/app/detail/[id]/index.tsx
- apps/admin/src/entities/check-post/api/getStudent.ts
- apps/admin/src/entities/check-post/model/useGetStudent.ts
- apps/admin/src/views/check-post/api/getPosts.ts
- apps/admin/src/views/check-post/model/useGetPosts.ts
- apps/admin/src/views/check-post/ui/posts.tsx
- apps/admin/src/views/detail/ui/index.tsx
- apps/client/src/shared/model/useGetCurrentMember.ts
- apps/client/src/views/detail/index.tsx
- apps/client/src/views/main/ui/index.tsx
> admin page 게시물 관련 로직을 수정했습니다
> fix: detail page requests

- apps/admin/src/views/score/api/featScore.ts
- apps/admin/src/views/score/model/score.ts
- apps/admin/src/views/score/ui/scoreForm.tsx
> fix: score page 기능 오류 해결

- apps/client/src/entities/main/model/certification.ts
> fix: certificate type

- apps/client/src/entities/posts/lib/useGetDraft.ts
- apps/client/src/entities/posts/lib/useGetPosts.ts
- apps/client/src/views/posts/api/getDraft.ts
- apps/client/src/views/posts/ui/myPosts.tsx
> fix: 게시물 오류를 고쳤습니다

- apps/client/src/entities/posts/api/getSearchResult.ts
- apps/client/src/entities/posts/ui/search.tsx
- apps/client/src/views/posts/ui/myPosts.tsx
> fix: 게시물 검색 기능 수정

- apps/client/src/entities/main/api/getCertification.ts
- apps/client/src/views/main/ui/index.tsx
> ex) #이슈번호, #이슈번호
#91 
https://github.com/user-attachments/assets/7269e0af-5c64-4b32-bb47-4151567d1c0b
certificate  삭제할 때는 어떻게 refetch할지
> fix: main certificate

- apps/client/src/views/example/index.tsx
- apps/client/src/views/posts/ui/myPosts.tsx
> posts page post 정렬 수정
> example page 제목 정렬 수정
https://github.com/user-attachments/assets/aab6e5a3-d023-461a-9b65-816be8f6e2d5
>
> fix: Posts style 변경

- apps/client/src/widgets/calculate/ui/index.tsx
> fix: 계산 페이지 오류 수정

- apps/admin/src/app/not-found.tsx
- apps/admin/src/entities/404/ui/Redirect404.tsx
- apps/client/src/app/not-found.tsx
- apps/client/src/entities/404/ui/Redirect404.tsx
> #117 
> 404가 뜨면 /로 redirect 시키는 로직을 작성했습니다
> feat: redirect 404

- apps/client/src/app/layout.tsx
- apps/client/src/shared/asset/svg/close.tsx
- apps/client/src/shared/asset/svg/hamburger.tsx
- apps/client/src/shared/ui/header/index.tsx
> style: header

- apps/admin/src/app/change-password/page.tsx
- apps/admin/src/entities/member/api/getSearchedMembers.ts
- apps/admin/src/middleware.ts
- apps/admin/src/shared/api/patchPassword.ts
- apps/admin/src/shared/model/AuthForm.ts
- apps/admin/src/shared/model/changePWForm.ts
- apps/admin/src/shared/ui/header.tsx
- apps/admin/src/views/change-password/index.tsx
- apps/admin/src/views/member/ui/index.tsx
- apps/admin/src/widgets/changePassword/ui/index.tsx
- apps/client/src/shared/api/patchPassword.ts
- apps/client/src/widgets/changePassword/ui/index.tsx
> #139 
> 헤더 기능 추가를 하고 검색을 고쳤습니다
> fix: header and search

- apps/client/src/views/detail/index.tsx
> #129
> 게시물 상세보기 반응형 적용했습니다.
https://github.com/user-attachments/assets/715af1ab-8874-46c8-aed8-3b4e507bf100
> style: 게시물 상세보기 반응형

- apps/client/src/shared/ui/file/index.tsx
> #146 
> 파일 이름 때문에 생기는 overflow를 막았습니다
> fix: hidden overflow

- apps/client/src/shared/api/patchPassword.ts
- apps/client/src/shared/model/changePWForm.ts
- apps/client/src/views/changePassword/ui/index.tsx
- apps/client/src/views/signup/ui/index.tsx
- apps/client/src/widgets/changePassword/ui/index.tsx
- apps/client/src/widgets/stepAuthCode/ui/index.tsx
> ex) #이슈번호, #이슈번호
#156 
비밀번호 변경 로직을 인증번호를 거치도록 수정하였습니다.
단언 타입(as)를 좀 써서 확인해주시면 좋을 것 같습니다.
아직 admin에는 적용안했습니다. ㅠ
> fix: change password

- apps/admin/src/views/detail/ui/index.tsx
> ex) #이슈번호, #이슈번호
> 어드민 게시물 상세보기 반응형
https://github.com/user-attachments/assets/bd72eceb-92c2-4294-aa50-a1a80bfa6952
> style: 어드민 게시물 상세보기 반응형

- apps/admin/src/views/score/api/featScore.ts
- apps/admin/src/views/score/model/score.ts
- apps/admin/src/views/score/ui/scoreForm.tsx
> ex) #이슈번호, #이슈번호
#177
score max value 서버와 일치시키기
score api 요청 수정 
https://github.com/user-attachments/assets/64185a5f-7ca2-4c28-94f2-3e041af7cd32
422 뜨는게 맞는지? -> max value 해결
점수를 부여하기 전/후의 점수 상태를 확인 할 수는 없는지? -> api 있음
> fix: score

- apps/admin/src/entities/member/model/score.ts
- apps/admin/src/entities/member/ui/scoreModal.tsx
> fix: score value
